[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "AOUNet"
version = "0.0.1"

[tool.setuptools]
packages = ["data", "data_prep", "graph", "common"]